
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import type { GenerateOptions } from '../types';

export async function generateScreen(name: string, options: GenerateOptions = {}): Promise<void> {
  const targetPath = options.path || path.join(process.cwd(), 'src/screens');
  const fileName = `${name}.tsx`;
  const filePath = path.join(targetPath, fileName);
  
  
  await fs.ensureDir(targetPath);
  
  
  const content = generateScreenContent(name);
  
  await fs.writeFile(filePath, content);
  
  console.log(chalk.green(`✓ Created ${fileName}`));
}

function generateScreenContent(name: string): string {
  const componentName = name.charAt(0).toUpperCase() + name.slice(1);
  
  return `import { View, Text, Button } from '@legion/runtime';
import { useNavigation } from '@legion/runtime/routing';

interface ${componentName}Props {
  
}

export function ${componentName}({}: ${componentName}Props) {
  const navigation = useNavigation();

  return (
    <View style={{ flex: 1, padding: 20 }}>
      <Text style={{ fontSize: 24, fontWeight: 'bold' }}>${componentName}</Text>
      <Text style={{ color: '#666', marginTop: 8 }}>
        Screen generated by Legion CLI
      </Text>
    </View>
  );
}

export default ${componentName};
`;
}
